### ISSUE TITLE
ACL295 sound distortion

### ISSUE THREAD

**Issue by RobinVanCauter** [s-light/ASUS-ZenBook-Pro-Duo-UX581GV#5]
I noticed a lot of incredible sound warp/distortion on the speakers (have not tried headphones yet) when audio is being played. The microphone is also pretty unusable, even at only 8% input level it records super loud static noise + a pop about every 10 seconds.

My initial research points towards ACL295 causing issues with the current linux kernel.

https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1648183
https://bugzilla.kernel.org/show_bug.cgi?id=195457

Both bug reports describe the issue in great detail and possible patches which I will look into later and report back after.

**Comment by s-light** [comment]
hm that is weird - 
i have no problem with sound. (kubuntu 19.10)

headphone output is not super loud but clean and has no distortion (even with full volume)
(only tested with my 250 Ohm Studio headphones - so that it is not super loud is expected.)
without headphones plugged in the speakers are active - there are no distortions - the sound is ok for a laptop. (little bass.. but that is expected) 

i have used the build in microphone to make voice calls and once to record an 'experiment' on a piano. i have recorded this with audacity - i only leveld the mic so that it does not clip - nothing else was modified -  from this i uploaded a short [example with some silence](http://blog.s-light.eu/wp-content/uploads/2019/12/Improvisation_SamstagAbend_part_with_silence.ogg) .
the fan is hear-able in this - but i think its fine for some quick tests / experiments... (the room was very silent)

**Comment by RobinVanCauter** [comment]
I'm going to close this for now, as I have not encountered the issue anymore since the day I created the issue.
